---
## Unseal HashiCorp Vault
# DO NOT USE THIS PLAYBOOK IN PRODUCTION!
# Extracted files (unseal keys, root token) are in plaintext, NOT ENCRYPTED!
# Created by simon
# Date: 25/11/2024

- name: Initialize, Unseal, Join HashiCorp Vault Pods in High Availability Deployment Type with TLS
  hosts: vault-cluster
  gather_facts: no
  vars_files:
    - ../variables/env.yml

  pre_tasks:
    - name: Ensure jq is installed
      homebrew:
        name: jq
        state: present

    # - name: Ensure Python is installed
    #   homebrew:
    #     name: python3
    #     state: present

    - name: Install kubernetes.core Ansible collection
      command: ansible-galaxy collection install kubernetes.core
      # args:
      #   creates: ~/.ansible/collections/ansible_collections/kubernetes/core
      ignore_errors: yes


    - name: Check and set replica count
      script: ../templates/check_replica_count.sh {{ namespace }} {{ replicas }}
      register: replica_count_output

    - name: Set replica count
      set_fact:
        replica_count: "{{ replica_count_output.stdout }}"

  tasks:
    - name: Initialize the first Vault `vault-0` pod
      kubernetes.core.k8s_exec:
        namespace: "{{ namespace }}"
        pod: "{{ vault_pod_0 }}"
        command: vault operator init
      register: init_output

    - name: Save Unseal Keys and Root Token
      copy:
        content: "{{ init_output.stdout }}"
        dest: /tmp/vault_init_output.txt

    - name: Extract Unseal Keys and Root Token
      script: ../templates/extract_unseal_keys.sh
      args:
        executable: /bin/bash

    - name: Unseal the first Vault pod
      script: ../templates/unseal_vault_pod.sh {{ namespace }} {{ vault_pod_0 }}
      args:
        executable: /bin/bash

    - name: Join and unseal remaining Vault pods
      script: ../templates/join_and_unseal_pods.sh {{ namespace }} {{ vault_pod_0 }} {{ replica_count }} {{ leader_ca_cert }}
      args:
        executable: /bin/bash

