---
## Unseal HashiCorp Vault
# DO NOT USE THIS PLAYBOOK IN PRODUCTION!
# Extracted files (unseal keys, root token) are in plaintext, NOT ENCRYPTED!
# Created by simon
# Date: 14/11/2024

- name: Initialize, Unseal, Join HashiCorp Vault Pods in High Availability Deployment Type
  hosts: vault-cluster
  gather_facts: no
  vars_files:
    - ../variables/env.yml

  pre_tasks:
    - name: Download extract_unseal_keys.sh script
      get_url:
        url: "{{ github_repo_url }}extract_unseal_keys.sh"
        dest: /tmp/extract_unseal_keys.sh
        mode: '0755'

    - name: Download unseal_vault_pod.sh script
      get_url:
        url: "{{ github_repo_url }}unseal_vault_pod.sh"
        dest: /tmp/unseal_vault_pod.sh
        mode: '0755'

    - name: Download join_and_unseal_pods.sh script
      get_url:
        url: "{{ github_repo_url }}join_and_unseal_pods.sh"
        dest: /tmp/join_and_unseal_pods.sh
        mode: '0755'

    - name: Check if HashiCorp Vault is installed with Helm
      command: helm list -n {{ namespace }} -q
      register: helm_list
      failed_when: "'vault' not in helm_list.stdout"

    - name: Get the number of replicas
      command: helm get values vault
      register: helm_values

    - name: Extract the number of replicas
      set_fact:
        replica_count: "{{ helm_values.stdout | regex_search('replicas: (\\d+)', '\\1') | int }}"

  tasks:
    - name: Initialize the first Vault `vault-0` pod
      kubernetes.core.k8s_exec:
        namespace: "{{ namespace }}"
        pod: "{{ vault_pod_0 }}"
        command: vault operator init
      register: init_output

    - name: Save Unseal Keys and Root Token
      copy:
        content: "{{ init_output.stdout }}"
        dest: /tmp/vault_init_output.txt

    - name: Extract Unseal Keys and Root Token
      script: ../templates/extract_unseal_keys.sh
      args:
        executable: /bin/bash

    - name: Unseal the first Vault pod
      script: ../templates/unseal_vault_pod.sh {{ namespace }} {{ vault_pod_0 }}
      args:
        executable: /bin/bash

    - name: Join and unseal remaining Vault pods
      script: ../templates/join_and_unseal_pods.sh {{ namespace }} {{ vault_pod_0 }} {{ replica_count }}
      args:
        executable: /bin/bash

  post_tasks:
    - name: Clean up temporary Bash Scripts from GitHub Repo
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/extract_unseal_keys.sh
        - /tmp/unseal_vault_pod.sh
        - /tmp/join_and_unseal_pods.sh