- name: Create X number of users with SSL keys
  hosts: "ansible-test-only"
  become: true

  vars_files:
    - ../variables/users-vars.yml

  pre_tasks:
    - name: Create the desired directory if not exists
      file:
        path: "{{ script_destination }}"
        state: directory
        # ignore_errors: true # does not exists, delete this line after testing

    - name: Download script from github
      get_url:
        url: https://raw.githubusercontent.com/POCOCZE/ELOS-Projekty/refs/heads/master/bash/{{ script_name }}
        dest: "{{ script_destination }}/{{ script_name }}"
        mode: '0755'

    - name: Change username in the script
      replace:
        path: "{{ script_destination }}/{{ script_name }}"
        regexp: 'USERNAME=.*'
        replace: 'USERNAME={{ username }}'

    - name: Change password in the script if needed
      replace:
        path: "{{ script_destination }}/{{ script_name }}"
        regexp: 'PASSWD=.*'
        replace: 'PASSWD={{ password }}'

  tasks:
    - name: Run the script
      become: true
      expect:
        command: "bash {{ script_destination }}/{{ script_name }}"
        responses:
          "Enter number of users to create:": "{{ users_count }}"

  post_tasks:
    - name: Delete the script
      file:
        path: "{{ script_destination }}/{{ script_name }}"
        state: absent # deletes the file

    - name: List files in working directory
      find:
        path: "{{ script_destination }}"
        recurse: true
      register: files_in_dir # save output to variable

    - name: Check if dir is empty
      set_fact:
        # `.files` is not a method but attributelength is Jinja2 filter
        is_empty: "{{ files_in_dir.files | length == 0 }}" # not used: and files_in_dir.directories | length == 0

    - name: Delete whole working directory if is_empty=True
      file:
        path: "{{ script_destination }}"
        state: absent
      when: is_empty 


