apiVersion: v1
kind: Service
metadata:
  name: {{ include "welcome-elos-webapp.fullname" . }}
  labels:
    {{- include "welcome-elos-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
# If the type field is not equal to ClusterIP AND the annotations field is not empty
{{- if (and (ne .Values.service.type "ClusterIP") .Values.service.annotations) }}
  annotations:
  # Print the annotations field as a YAML string, indented by 4 spaces
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  selector:
    {{- include "welcome-elos-webapp.selectorLabels" . | nindent 4 }}
